### ISSUE TITLE
Graphs 2.0

### ISSUE THREAD

**Issue by cpfiffer** [JuliaGraphs/GraphsBase.jl#33]
Is there a graphs 2.0 discussion somewhere? I wasn't able to find it. If so, could you point me to it? If not, could this be a good meta-thread to store that discussion?

**Comment by cpfiffer** [comment]
Ah, found it:

- https://github.com/JuliaGraphs/Graphs.jl/issues/128
- https://github.com/JuliaGraphs/Graphs.jl/issues/146
- https://github.com/JuliaGraphs/Graphs.jl/issues/165

**Comment by etiennedeg** [comment]
Also, most of the discussions about the interface happen on [GraphsBase](https://github.com/JuliaGraphs/GraphsBase.jl/issues)
